added title and publish date for video schema
aemsites/danaher-abcam pull request #253
Opened 2024-10-13 10:42 UTC by pardeepgera23

Fix #247 

Test URLs:
- Before: https://main--danaher-abcam--aemsites.hlx.page/en-us/stories/films/maryann-martone
- After: https://247-video-schema--danaher-abcam--aemsites.hlx.page/en-us/stories/films/maryann-martone

2024-10-14 07:02 UTC, rgravitvl commented on eds/scripts/schema.js
> +    uploadDate: getMetadata('publishdate'),
I guess, this would be temporary solution. The permanent solution would be either get information from youtube video or author the required informations.

2024-10-14 15:07 UTC, davenichols-DHLS commented on eds/scripts/schema.js
> +    uploadDate: getMetadata('publishdate'),
Yes, sorry - this would be the quick solution to solve this.

2024-10-14 15:08 UTC, davenichols-DHLS approved these changes
LGTM

2024-10-15 06:52 UTC, sharanagoudapatil approved these changes

2024-10-15 09:17 UTC, davenichols-DHLS requested changes
@pardeepgera23  - it's passing name but not date:

https://validator.schema.org/#url=https%3A%2F%2F247-video-schema--danaher-abcam--aemsites.hlx.page%2Fen-us%2Fstories%2Ffilms%2Frobert-blelloch

2024-10-16 13:39 UTC, davenichols-DHLS commented
Sorry @pardeepgera23  - I tested this but still the date is not in the schema?

https://validator.schema.org/#url=https%3A%2F%2F247-video-schema--danaher-abcam--aemsites.hlx.page%2Fen-us%2Fstories%2Ffilms%2Fmaryann-martone

2024-10-16 14:02 UTC, davenichols-DHLS commented
> > Sorry @pardeepgera23 - I tested this but still the date is not in the schema?
> > https://validator.schema.org/#url=https%3A%2F%2F247-video-schema--danaher-abcam--aemsites.hlx.page%2Fen-us%2Fstories%2Ffilms%2Fmaryann-martone
> 
> @davenichols-DHLS - I have now added the publishedDate field in media metadata which is not yet authored. Once we merge this and author the media properties, we should be able to see the changes in schema.

Got it, sorry - I misunderstood.  In that case, I am good with this.  @rgravitvl , can we merge please?

2024-10-16 14:02 UTC, davenichols-DHLS approved these changes
Good to go, thanks.

2024-10-16 14:52 UTC, merged