Task 259 - Sticky Navigation
aemsites/danaher-abcam pull request #274
Opened 2024-10-16 17:08 UTC by amlan18041996

Fix #259 

Test URLs:
- Before: https://main--danaher-abcam--aemsites.hlx.live/en-us/technical-resources/guides/elisa-guide
- After: https://259-sticky-navigation--danaher-abcam--aemsites.hlx.live/en-us/technical-resources/guides/elisa-guide

2024-10-17 11:19 UTC, sharanagoudapatil reviewed
![image](https://github.com/user-attachments/assets/e8081cda-5584-4c4d-9df1-0739015d64ec)

- Please rename block name from 'sticky-links' to 'related-links' (just for the meaningful name). 
- Replace 'Sticky Links' with 'Related Links' in model definitions as well.
- Fix lint errors also as part of the code/build.

2024-10-17 14:13 UTC, amlan18041996 commented
> ![image](https://private-user-images.githubusercontent.com/141244748/377439546-e8081cda-5584-4c4d-9df1-0739015d64ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjQzOTYsIm5iZiI6MTcyOTE2NDA5NiwicGF0aCI6Ii8xNDEyNDQ3NDgvMzc3NDM5NTQ2LWU4MDgxY2RhLTU1ODQtNGM0ZC05ZGYxLTA3MzkwMTVkNjRlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxMTIxMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmU0Y2NmMjNhYTIxMzljZGIzMDFmMmRmM2UzYWIwYzRlNjMxNzg4MTQ4NjQyMzEwMWFmNGQ1NTlhY2ViODRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A6Rn_YbaQngLqv_2PiGKzcM7zJS0n4GdYi4xqwmVF8w)
> 
> * Please rename block name from 'sticky-links' to 'related-links' (just for the meaningful name).
> * Replace 'Sticky Links' with 'Related Links' in model definitions as well.
> * Fix lint errors also as part of the code/build.

Kindly check it again as I made the changes which are listed here.

2024-10-23 09:57 UTC, rgravitvl requested changes

2024-10-23 09:57 UTC, rgravitvl commented on eds/blocks/related-links/_related-links.json
> +{
Are we still using related-links??

2024-10-23 09:57 UTC, rgravitvl commented on eds/templates/guides/guides.js
> +import { buildBlock, getMetadata } from '../../scripts/aem.js';
there is already guide template, please check

2024-10-23 10:17 UTC, rgravitvl approved these changes

2024-10-23 10:46 UTC, pardeepgera23 approved these changes

2024-10-23 11:17 UTC, shivangi1422 approved these changes

2024-10-23 18:46 UTC, merged