32 component modeling
aemsites/danaher-abcam pull request #34
Opened 2024-08-09 15:33 UTC by shivangi1422

Component Modelling changes for Card, Mini-Teasers and Alternating blocks.

Fix #32 

Test URLs:
- Before: https://main--{repo}--{owner}.hlx.live/
- After: https://<branch>--{repo}--{owner}.hlx.live/

2024-08-12 04:37 UTC, pardeepgera23 approved these changes

2024-08-12 14:47 UTC, rgravitvl requested changes
@shivangi1422  We have review the model JSON, can we connect tomorrow morning 10:30am??

2024-08-12 14:47 UTC, rgravitvl commented on component-definition.json
> +                    "name": "Mini-Teasers",
Model also to be added here as : "model": ""mini-teasers",

2024-08-12 14:47 UTC, rgravitvl commented on component-models.json
> +          "label": "CTA Title"
How does differentiate from CTA Text? I see both are component type as text

2024-08-12 14:47 UTC, rgravitvl commented on component-models.json
> +              "name": "h5",
Do we really need all these heading types??

2024-08-13 06:16 UTC, pardeepgera23 approved these changes

2024-08-13 06:16 UTC, rgravitvl approved these changes

2024-08-13 06:17 UTC, merged