306 video transcript
aemsites/danaher-abcam pull request #349
Opened 2024-10-30 05:00 UTC by vishnu-gspann

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--danaher-abcam--aemsites.hlx.live/
- After: https://306-transcript-video--danaher-abcam--aemsites.hlx.live/en-us/page-test

2024-11-06 11:23 UTC, rgravitvl requested changes

2024-11-06 11:23 UTC, rgravitvl commented on eds/blocks/video-transcript/video-transcript.js
> +import { decorateIcons } from '../../scripts/aem.js';
Let's not create new DOM Element instead we can use as is that we get from Author.

2024-11-11 05:44 UTC, rgravitvl approved these changes

2024-11-11 05:44 UTC, rgravitvl approved these changes

2024-11-11 06:54 UTC, pardeepgera23 approved these changes

2024-11-11 13:21 UTC, merged