removed html extension from schema json
aemsites/danaher-abcam pull request #352
Opened 2024-10-30 10:47 UTC by pardeepgera23

Before: https://main--danaher-abcam--aemsites.hlx.page/en-us/technical-resources/guides
After: https://schema-fix--danaher-abcam--aemsites.hlx.page/en-us/technical-resources/guides

2024-10-30 13:10 UTC, sharanagoudapatil requested changes

2024-10-30 13:10 UTC, sharanagoudapatil commented on eds/scripts/scripts.js
> -export function makePublicUrl(url) {
Please don't delete/remove this common function from scripts.js. It's been called/used in other blocks.
For example - we used in chapter-links.js.

2024-10-30 13:35 UTC, pardeepgera23 commented on eds/scripts/scripts.js
> -export function makePublicUrl(url) {
This function call has been removed from chapter-links.js today during go-live as we noticed this was leading to .html extension getting appended to all chapter link url's. Apart from that, it was only being used in schema.js and i think its no longer needed.

2024-11-05 13:37 UTC, sharanagoudapatil approved these changes

2024-11-05 13:48 UTC, merged