357 topics library page template
aemsites/danaher-abcam pull request #370
Opened 2024-11-05 10:22 UTC by vishnu-gspann

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #357 

Test URLs:
- Before: https://main--danaher-abcam--aemsites.hlx.live/
- After: https://357-topics-library-page-template--danaher-abcam--aemsites.hlx.live/en-us/vs-topics-page-template-test/vs-topic-2

2024-11-06 09:00 UTC, pardeepgera23 approved these changes

2024-11-06 09:46 UTC, rgravitvl requested changes

2024-11-06 09:46 UTC, rgravitvl commented on build-css.js
> +    output: './eds/templates/topics/topics.css',
Please rename it topic, instead of topics

2024-11-08 06:13 UTC, rgravitvl approved these changes

2024-11-08 07:42 UTC, merged