174 webinar related content
aemsites/danaher-abcam pull request #406
Opened 2024-11-13 11:54 UTC by venkateshamkeerthi

changes done for webinar related-stories but this can be tested after indexing data updated for webinar,
this component is used for stories also, we are testing stories pages also, shouldn't impact other pages

Fix #174 

Test URLs:
- Before: https://main--danaher-abcam--aemsites.hlx.live/en-us/stories/articles/simplify-your-assay-design-with-our-matched-antibody-pairs
- After:  https://174-webinar-related-content--danaher-abcam--aemsites.hlx.live/en-us/stories/articles/simplify-your-assay-design-with-our-matched-antibody-pairs

2024-11-13 14:31 UTC, rgravitvl commented on eds/blocks/related-stories/related-stories.js
>      : article.title;
why don't we use createCard from articleCard.js here??

2024-11-13 14:31 UTC, rgravitvl requested changes
why don't we use createCard from articleCard.js here??

2024-11-14 06:10 UTC, venkateshamkeerthi commented on eds/blocks/related-stories/related-stories.js
>      : article.title;
styling is different for hub page and related--stories cards(https://174-webinar-related-content--danaher-abcam--aemsites.hlx.live/en-us/stories/articles/simplify-your-assay-design-with-our-matched-antibody-pairs)
ex: https://174-webinar-related-content--danaher-abcam--aemsites.hlx.live/en-us/stories and
https://174-webinar-related-content--danaher-abcam--aemsites.hlx.live/en-us/stories/articles/simplify-your-assay-design-with-our-matched-antibody-pairs

"Read Article"  link and on mouseover image scale-up(zoom)

2024-11-14 08:50 UTC, venkateshamkeerthi commented on eds/blocks/related-stories/related-stories.js
>      : article.title;
Hi @rgravitvl  I changed logic changed to  createCard from articleCard.js

2024-11-18 05:29 UTC, rgravitvl approved these changes

2024-11-18 06:17 UTC, pardeepgera23 approved these changes

2024-11-18 06:18 UTC, merged