Fixes For [Webinar] Issues With Breadcrumb || Form #450
aemsites/danaher-abcam pull request #471
Opened 2024-11-26 07:31 UTC by kumarshoolam

Test URLs:
- Before: https://main--danaher-abcam--aemsites.aem.live/en-us/webinars/webinar-two
- After: https://450-webinar-bc-issues--danaher-abcam--aemsites.aem.live/en-us/webinars/webinar-two

2024-11-26 09:39 UTC, rgravitvl requested changes

2024-11-26 10:16 UTC, kumarshoolam commented
Hi @rgravitvl 
I have Addressed your comment,
Removed the commented code in Elouqa-form file.
Thanks!

2024-11-27 10:12 UTC, rgravitvl approved these changes

2024-11-28 04:12 UTC, pardeepgera23 approved these changes

2024-11-28 04:12 UTC, merged