386 header cart api fetch
aemsites/danaher-abcam pull request #473
Opened 2024-11-26 11:43 UTC by kumarshoolam

Fix #386 

Test URLs:
- Before: https://main--danaher-abcam--aemsites.aem.live/en-us/webinars/webinar-two
- After: https://386-headercart-api-fetch--danaher-abcam--aemsites.aem.live/en-us/webinars/webinar-two

2024-11-26 14:33 UTC, pardeepgera23 commented on eds/blocks/header/header.js
> +          throw new Error(`HTTP error! Status: ${response.status}`);
log error in console

2024-11-26 14:35 UTC, pardeepgera23 commented on eds/blocks/header/header.js
> +    : 'pp.abcam.com';
no need to point to pp.abcam.com. Use window.location.host only.

2024-11-26 14:36 UTC, pardeepgera23 requested changes
added comments

2024-11-26 17:09 UTC, kumarshoolam commented on eds/blocks/header/header.js
> +        'Content-Type': 'application/json',
Hello @pardeepgera23 
Addressed PR Review Comments & Made Changes Accordingly-386.
CC: @Meenu-GSPANN, @Rajesh-GSPANN

2024-11-26 17:09 UTC, kumarshoolam commented on eds/blocks/header/header.js
> +          throw new Error(`HTTP error! Status: ${response.status}`);
Hello @pardeepgera23 
Addressed PR Review Comments & Made Changes Accordingly-386.
CC: @Meenu-GSPANN, @Rajesh-GSPANN

2024-11-26 17:09 UTC, kumarshoolam commented on eds/blocks/header/header.js
> +    : 'pp.abcam.com';
Hello @pardeepgera23 
Addressed PR Review Comments & Made Changes Accordingly-386.
CC: @Meenu-GSPANN, @Rajesh-GSPANN

2024-11-27 03:29 UTC, pardeepgera23 commented on eds/blocks/header/header.js
> +          throw new Error(`HTTP error! Status: ${response.status}`);
Use // eslint-disable-next-line no-console

2024-11-27 03:31 UTC, pardeepgera23 commented on eds/blocks/header/header.js
> +      alert(`You have ${productCount} products in your cart!`);
Either use modal popup instead of alert or ignore the eslint for alert using // eslint-disable-next-line no-alert

2024-11-27 09:44 UTC, pardeepgera23 approved these changes

2024-11-27 10:04 UTC, rgravitvl approved these changes
Please address the redirect empty cart page, x-correlation-id and rest looks good to me

2024-11-27 10:39 UTC, merged

2024-11-27 10:44 UTC, kumarshoolam commented
Hello @rgravitvl 

As we discussed, We have Addressed PR Comments regarding empty cart page redirection, x-correlation-id and worked accordingly.

CC: @Meenu-GSPANN , @pardeepgera23 , @Rajesh-GSPANN