Revised CTA Banner CSS changes - 579
aemsites/danaher-abcam pull request #584
Opened 2024-12-13 09:26 UTC by nagaraju-gspann

Fix #579

Test URLs:
- Before: https://main--danaher-abcam--aemsites.hlx.page/en-us/page-test/cta-description
- After: https://579-CTA-CSS-Changes--danaher-abcam--aemsites.hlx.live/en-us/page-test/cta-description

2024-12-13 09:50 UTC, shivangi1422 commented on eds/blocks/cta-banner/cta-banner.js
> -  applyClasses(title, 'title mt-0 mb-4 !leading-[22px] !font-bold text-xl text-[#378189] break-words');
make text-xl as important i.e !text-xl. It is taking the styling for h3 rather than text-xl

2024-12-13 10:21 UTC, nagaraju-gspann commented
- Modified CSS changes according to revised Figma.
- Addressed & Fixed the review comments.
- Pushed and Raised PR.  

CC: @Meenu-GSPANN , @shivangi1422, @pardeepgera23

2024-12-13 11:01 UTC, shivangi1422 approved these changes

2024-12-16 11:17 UTC, pardeepgera23 requested changes

2024-12-16 11:17 UTC, pardeepgera23 commented on eds/blocks/cta-banner/cta-banner.js
> +  block.classList.add(...'cta-container flex md:items-center flex-col md:flex-row justify-between gap-6 md:gap-8 w-full p-6 mt-10 mb-14 rounded-xl bg-[#edf6f7]'.split(' '));
Use applyClasses from scripts.js

2024-12-17 03:36 UTC, nagaraju-gspann commented on eds/blocks/cta-banner/cta-banner.js
> +  block.classList.add(...'cta-container flex md:items-center flex-col md:flex-row justify-between gap-6 md:gap-8 w-full p-6 mt-10 mb-14 rounded-xl bg-[#edf6f7]'.split(' '));
Fixed review comments.

2024-12-17 09:03 UTC, pardeepgera23 approved these changes

2024-12-17 09:03 UTC, merged