Cart functionality in Header fragment
aemsites/danaher-abcam pull request #621
Opened 2024-12-30 05:55 UTC by Rajesh-GSPANN

Fix #620 

Test URLs:
- Before: https://main--danaher-abcam--aemsites.hlx.page/en-us/webinars/antibody-to-assay-the-key-to-consistent-and-reproducible-immunoassay-results
- After: https://532-header-fragment-cartimpl--danaher-abcam--aemsites.hlx.page/en-us/webinars/antibody-to-assay-the-key-to-consistent-and-reproducible-immunoassay-results

2024-12-30 06:24 UTC, pardeepgera23 requested changes

2024-12-30 06:24 UTC, pardeepgera23 commented on eds/blocks/header/header.js
> +  // basicDetails().shoppingBaskedId !== null && basicDetails().shoppingBaskedId
Remove commented lines of code

2024-12-30 07:11 UTC, Rajesh-GSPANN commented on eds/blocks/header/header.js
> +  // basicDetails().shoppingBaskedId !== null && basicDetails().shoppingBaskedId
Hi @pardeepgera23 ,
Removed the comments and pushed

2025-01-03 03:05 UTC, pardeepgera23 requested changes

2025-01-03 03:05 UTC, pardeepgera23 commented on eds/blocks/header/header.js
> +              label({ class: 'font-semibold' }, 'Enter product codes below and click "add products"'),
Do not use hardcoded labels in html...define key-values and then use keys in html so that later the keys can be used for placeholders and translations

2025-01-06 07:25 UTC, Rajesh-GSPANN commented on eds/blocks/header/header.js
> +              label({ class: 'font-semibold' }, 'Enter product codes below and click "add products"'),
@pardeepgera23 
Moved to Key value pair

2025-01-06 07:26 UTC, Rajesh-GSPANN commented on eds/blocks/header/header.js
> +        // span({ class: 'line-item hidden'},item.lineNumber),
@pardeepgera23 ,
Removed the commented lines.

2025-01-06 07:26 UTC, Rajesh-GSPANN commented on eds/blocks/header/header.js
> +} from './header-api-calls.js';
Hi @pardeepgera23 ,
Updated the file name

2025-01-06 18:02 UTC, pardeepgera23 approved these changes

2025-01-08 10:36 UTC, davenichols-DHLS approved these changes
LGTM

2025-01-08 10:36 UTC, merged